"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5qcxe7KhdJT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import DropdownMenu from "@/components/ui/DropDownMenu"

export default function studymainpage() {
  return (
    <div className="flex h-screen w-full flex-col">
      <header className="flex items-center justify-between bg-primary px-6 py-4 text-primary-foreground">
        <div className="flex items-center gap-4">
          <DropdownMenu></DropdownMenu>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="rounded-full">
            <SearchIcon className="h-5 w-5" />
            <span className="sr-only">Search</span>
          </Button>
          <Button variant="ghost" size="icon" className="rounded-full">
            <img
              src="/placeholder.svg"
              width="32"
              height="32"
              className="rounded-full"
              alt="Avatar"
              style={{ aspectRatio: "32/32", objectFit: "cover" }}
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <div className="flex flex-1">
        <div className="hidden w-64 flex-col border-r bg-background p-6 md:flex">
          <div className="mb-6">
            <h3 className="text-lg font-medium">Navigation</h3>
            <nav className="mt-4 space-y-1">
              <Link
                href="#"
                className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                <CircuitBoardIcon className="h-5 w-5" />
                Board
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                <StepForwardIcon className="h-5 w-5" />
                Progress
              </Link>
            </nav>
          </div>
          <div className="flex-1 overflow-auto">
            <h3 className="text-lg font-medium">Members</h3>
            <button>plus</button>
            <div className="mt-4 space-y-2">
              <div className="flex items-center gap-2">
                <Avatar className="h-8 w-8">
                  <AvatarImage src="/placeholder-user.jpg" alt="User 1" />
                  <AvatarFallback>U1</AvatarFallback>
                </Avatar>
                <div>
                  <p className="text-sm font-medium">John Doe</p>
                  <p className="text-xs text-muted-foreground">Studying Computer Science</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Avatar className="h-8 w-8">
                  <AvatarImage src="/placeholder-user.jpg" alt="User 2" />
                  <AvatarFallback>U2</AvatarFallback>
                </Avatar>
                <div>
                  <p className="text-sm font-medium">Jane Smith</p>
                  <p className="text-xs text-muted-foreground">Studying Mathematics</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Avatar className="h-8 w-8">
                  <AvatarImage src="/placeholder-user.jpg" alt="User 3" />
                  <AvatarFallback>U3</AvatarFallback>
                </Avatar>
                <div>
                  <p className="text-sm font-medium">Alex Johnson</p>
                  <p className="text-xs text-muted-foreground">Studying Physics</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex-1 p-6">
          <div className="mb-6">
            <h2 className="text-2xl font-bold">Study Group Board</h2>
            <div className="mt-4 space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Calculus Homework</CardTitle>
                  <CardDescription>Review and complete the assigned calculus homework for this week.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p>The calculus homework for this week covers the following topics:</p>
                    <ul className="list-disc pl-6">
                      <li>Limits and continuity</li>
                      <li>Derivatives and their applications</li>
                      <li>Optimization problems</li>
                    </ul>
                    <p>Please review the assigned problems and submit your solutions by the end of the week.</p>
                  </div>
                </CardContent>
                <CardFooter className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Avatar className="h-6 w-6">
                      <AvatarImage src="/placeholder-user.jpg" alt="User 1" />
                      <AvatarFallback>U1</AvatarFallback>
                    </Avatar>
                    <p className="text-sm">John Doe</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button variant="ghost" size="icon">
                      <MessageCircleIcon className="h-5 w-5" />
                      <span className="sr-only">Comment</span>
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ThumbsUpIcon className="h-5 w-5" />
                      <span className="sr-only">Like</span>
                    </Button>
                  </div>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Physics Lab Report</CardTitle>
                  <CardDescription>Prepare the lab report for the recent physics experiment.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p>The physics lab report should include the following sections:</p>
                    <ul className="list-disc pl-6">
                      <li>Abstract</li>
                      <li>Introduction</li>
                      <li>Methodology</li>
                      <li>Results and Discussion</li>
                      <li>Conclusion</li>
                    </ul>
                    <p>Please submit the completed report by the end of the week.</p>
                  </div>
                </CardContent>
                <CardFooter className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Avatar className="h-6 w-6">
                      <AvatarImage src="/placeholder-user.jpg" alt="User 2" />
                      <AvatarFallback>U2</AvatarFallback>
                    </Avatar>
                    <p className="text-sm">Jane Smith</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button variant="ghost" size="icon">
                      <MessageCircleIcon className="h-5 w-5" />
                      <span className="sr-only">Comment</span>
                    </Button>
                    <Button variant="ghost" size="icon">
                      <ThumbsUpIcon className="h-5 w-5" />
                      <span className="sr-only">Like</span>
                    </Button>
                  </div>
                </CardFooter>
              </Card>
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold">Study Progress</h2>
            <div className="mt-4 space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Overall Progress</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="flex items-center gap-2">
                      <div className="flex-1">
                        <p className="text-sm font-medium">John Doe</p>
                        <Progress value={75} />
                      </div>
                      <p className="text-sm">75%</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="flex-1">
                        <p className="text-sm font-medium">Jane Smith</p>
                        <Progress value={80} />
                      </div>
                      <p className="text-sm">80%</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="flex-1">
                        <p className="text-sm font-medium">Alex Johnson</p>
                        <Progress value={65} />
                      </div>
                      <p className="text-sm">65%</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function CircuitBoardIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M11 9h4a2 2 0 0 0 2-2V3" />
      <circle cx="9" cy="9" r="2" />
      <path d="M7 21v-4a2 2 0 0 1 2-2h4" />
      <circle cx="15" cy="15" r="2" />
    </svg>
  )
}


function MessageCircleIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function SearchIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function StepForwardIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="6" x2="6" y1="4" y2="20" />
      <polygon points="10,4 20,12 10,20" />
    </svg>
  )
}


function ThumbsUpIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
