/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Qxi2ry8guma
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Progress } from "@/components/ui/progress"

export default function mainpage() {
  return (
    <div className="flex flex-col h-full w-full max-w-6xl mx-auto p-4 md:p-6">
      <div className="flex flex-col md:flex-row gap-6">
        <div className="flex-1 bg-card rounded-lg shadow-lg overflow-hidden">
          <div className="bg-card-foreground p-4 md:p-6 border-b">
            <h2 className="text-lg font-semibold">Study Group Board</h2>
          </div>
          <div className="p-4 md:p-6 space-y-6">
            <div>
              <h3 className="text-sm font-medium mb-2">Updates</h3>
              <div className="bg-muted rounded-lg p-4 space-y-4">
                <div className="flex items-start gap-4">
                  <div className="rounded-full bg-primary text-primary-foreground w-8 h-8 flex items-center justify-center">
                    <FilePenIcon className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="font-medium">New study material added</p>
                    <p className="text-muted-foreground text-sm">Check out the latest chapter on linear algebra.</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="rounded-full bg-primary text-primary-foreground w-8 h-8 flex items-center justify-center">
                    <CalendarIcon className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="font-medium">Upcoming study session</p>
                    <p className="text-muted-foreground text-sm">
                      Join us this Saturday at 2pm for a group study session.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h3 className="text-sm font-medium mb-2">Resources</h3>
              <div className="bg-muted rounded-lg p-4 space-y-4">
                <div className="flex items-start gap-4">
                  <div className="rounded-full bg-primary text-primary-foreground w-8 h-8 flex items-center justify-center">
                    <FileIcon className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="font-medium">Linear Algebra Textbook</p>
                    <p className="text-muted-foreground text-sm">Download the latest edition of the textbook.</p>
                    <Button variant="secondary" size="sm" className="mt-2">
                      Download
                    </Button>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="rounded-full bg-primary text-primary-foreground w-8 h-8 flex items-center justify-center">
                    <LinkIcon className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="font-medium">Online Practice Exercises</p>
                    <p className="text-muted-foreground text-sm">Check out these interactive practice problems.</p>
                    <Link href="#" className="text-primary underline text-sm" prefetch={false}>
                      Visit site
                    </Link>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h3 className="text-sm font-medium mb-2">Discussion</h3>
              <div className="bg-muted rounded-lg p-4 space-y-4">
                <div className="flex items-start gap-4">
                  <Avatar className="w-8 h-8">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <p className="font-medium">John Doe</p>
                    <p className="text-muted-foreground text-sm">
                      {`I'm struggling with the matrix operations section, any tips?`}
                    </p>
                    <div className="flex items-center gap-2 mt-2">
                      <Button variant="ghost" size="icon">
                        <ThumbsUpIcon className="w-4 h-4" />
                      </Button>
                      <Button variant="ghost" size="icon">
                        <MessageCircleIcon className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar className="w-8 h-8">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>SA</AvatarFallback>
                  </Avatar>
                  <div>
                    <p className="font-medium">Sarah Anderson</p>
                    <p className="text-muted-foreground text-sm">
                      The practice exercises on the website really helped me understand the concepts better.
                    </p>
                    <div className="flex items-center gap-2 mt-2">
                      <Button variant="ghost" size="icon">
                        <ThumbsUpIcon className="w-4 h-4" />
                      </Button>
                      <Button variant="ghost" size="icon">
                        <MessageCircleIcon className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex-1 bg-card rounded-lg shadow-lg overflow-hidden">
          <div className="bg-card-foreground p-4 md:p-6 border-b">
            <h2 className="text-lg font-semibold">Study Progress</h2>
          </div>
          <div className="p-4 md:p-6 space-y-6">
            <div>
              <h3 className="text-sm font-medium mb-2">Overall Progress</h3>
              <Progress value={75} className="h-4" />
              <p className="text-muted-foreground text-sm mt-2">75% of the course material has been covered.</p>
            </div>
            <div>
              <h3 className="text-sm font-medium mb-2">Individual Progress</h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Avatar className="w-8 h-8">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <p>John Doe</p>
                  </div>
                  <Progress value={80} className="w-32 h-4" />
                  <p className="text-muted-foreground text-sm">80%</p>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Avatar className="w-8 h-8">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>SA</AvatarFallback>
                    </Avatar>
                    <p>Sarah Anderson</p>
                  </div>
                  <Progress value={65} className="w-32 h-4" />
                  <p className="text-muted-foreground text-sm">65%</p>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Avatar className="w-8 h-8">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>MI</AvatarFallback>
                    </Avatar>
                    <p>Michael Ivanov</p>
                  </div>
                  <Progress value={72} className="w-32 h-4" />
                  <p className="text-muted-foreground text-sm">72%</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function CalendarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function FileIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}


function FilePenIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function LinkIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}


function MessageCircleIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}


function ThumbsUpIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
